package com.zqk.community.mapper;

import com.zqk.community.model.Like;
import com.zqk.community.model.LikeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface LikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likerecord
     *
     * @mbg.generated Sat May 30 18:43:48 CST 2020
     */
    long countByExample(LikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likerecord
     *
     * @mbg.generated Sat May 30 18:43:48 CST 2020
     */
    int deleteByExample(LikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likerecord
     *
     * @mbg.generated Sat May 30 18:43:48 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likerecord
     *
     * @mbg.generated Sat May 30 18:43:48 CST 2020
     */
    int insert(Like record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likerecord
     *
     * @mbg.generated Sat May 30 18:43:48 CST 2020
     */
    int insertSelective(Like record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likerecord
     *
     * @mbg.generated Sat May 30 18:43:48 CST 2020
     */
    List<Like> selectByExampleWithRowbounds(LikeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likerecord
     *
     * @mbg.generated Sat May 30 18:43:48 CST 2020
     */
    List<Like> selectByExample(LikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likerecord
     *
     * @mbg.generated Sat May 30 18:43:48 CST 2020
     */
    Like selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likerecord
     *
     * @mbg.generated Sat May 30 18:43:48 CST 2020
     */
    int updateByExampleSelective(@Param("record") Like record, @Param("example") LikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likerecord
     *
     * @mbg.generated Sat May 30 18:43:48 CST 2020
     */
    int updateByExample(@Param("record") Like record, @Param("example") LikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likerecord
     *
     * @mbg.generated Sat May 30 18:43:48 CST 2020
     */
    int updateByPrimaryKeySelective(Like record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likerecord
     *
     * @mbg.generated Sat May 30 18:43:48 CST 2020
     */
    int updateByPrimaryKey(Like record);
}